### ISSUE TITLE
libsfml-*.so.2 symlinks not being created anymore

### ISSUE THREAD

**Issue by Mischa-Alff** [LaurentGomila/SFML#761]
When building SFML with CMake on Linux (ArchLinux x86_64 in my case), and `make install`ing, the `libsfml-*.so.2` symlinks are no longer created. I'm not sure whether this was intentional or not, but currently, it breaks already compiled software that depended on that symlink.

**Comment by mantognini** [comment]
So in a nutshell (and avoid further misunderstanding), is this an issue or not -- in other words, should it be closed or properly tagged?

**Comment by TankOs** [comment]
It depends on our final decision. I'm (still) with binary1248, in which case this could be closed as "not an issue". ;) But we have to discuss it on the forum.

**Comment by eXpl0it3r** [comment]
The decision has been made that only two positions (major & minor) get used for the soversion.
So is this still an issue?

**Comment by binary1248** [comment]
Well... CMake would have to be adjusted... again :stuck_out_tongue:.

**Comment by eXpl0it3r** [comment]
That I'm aware of, but what about the sym link issue etc.
As a barely Linux user I don't fully understand the issue.

**Comment by binary1248** [comment]
Well... if I remove the ${VERSION_PATCH} from [this line](https://github.com/LaurentGomila/SFML/blob/master/cmake/Macros.cmake#L45), the correct links are created again.

libsfml-system.so -> libsfml-system.so.2.2
libsfml-system.so.2.2 -> libsfml-system.so.2.2.0
libsfml-system.so.2.2.0

There is intentionally no libsfml-system.so.2 because that is reserved for the 2.0/2.1 ABI, which is not compatible with the 2.2 ABI.

**Comment by eXpl0it3r** [comment]
With the SOVERSION change in #812 this issue will vanish.
