### ISSUE TITLE
Audio module fails to open one paged ogg/vorbis audio files

### ISSUE THREAD

**Issue by LaurentGomila** [LaurentGomila/SFML#845]
Description and test files: http://en.sfml-dev.org/forums/index.php?topic=17788.0

The problem is in ```FileInputStream```: once the internal file has reached its end, it is in fail/eof state and all its functions return junk. Clearing the error bits at the beginning of ```FileInputStream::getSize```(the one that makes the ogg/vorbis reader fail) makes the FLAC reader enter an infinite loop for some reason.

I'm about to switch the implementation to the good old FILE* API. Unless someone finds a clean way to handle this stuff :grin:

**Comment by binary1248** [comment]
Like I said [here](https://github.com/LaurentGomila/SFML/issues/647#issuecomment-75916727), the cleanest way would probably be to implement our own high level file stream classes that provided support for UTF-8 filenames and prevented this kind of stuff from happening.

**Comment by LaurentGomila** [comment]
> implement our own high level file stream classes 

They would be based on what? The OS API?

**Comment by binary1248** [comment]
Of course :wink:.

Since std::fstream doesn't support UTF-8 filenames on Windows, we would have to end up using the OS API for that there anyway. Same story on Linux and OS X although they do support UTF-8 filenames in std::fstream AFAIK. sf::FileInputStream isn't much else but a thin wrapper around std::ifstream now, and as you noticed in this issue, it just isn't enough for us. If we threw out the std::ifstream and replaced it with implementations for each OS, we will have more control and be able to shape the behaviour according to our (and ultimately the user's) requirements. In this case, it would make more sense to generalize the class to not only input but output as well.

**Comment by LaurentGomila** [comment]
That makes sense. But we should still find a solution to this bug until we reimplement file streams.

**Comment by eXpl0it3r** [comment]
Having looked at the source for the other issue, I know that when reading from memory the first few bytes get read to check what format the data is in. If the stream now reaches its end, it will fail with EOF. Maybe one needs to call clear() after these tests.
Though I'm not sure how it works when read from a file.

**Comment by LaurentGomila** [comment]
The problem is *when* to call ```clear()```. It is already called in ```FileInputStream::seek```, and that should be enough because that's what the ogg/vorbis reader tries to do after EOF has been reached. But it tries to seek at the end of the file, and what the implementation does in this case is ```stream->seek(stream->getSize())```. So ```getSize``` is called before ```seek```, and it is the one that fails. And as already stated, we cannot simply call ```clear()``` there.

**Comment by Bromeon** [comment]
Is there a reason why we compute the file size every time `getSize()` is called, instead of storing it?

**Comment by eXpl0it3r** [comment]
The problem originates from Vorbis. Not sure if we're not following their way or if there's another issue. I'm currently looking into it.

**Comment by LaurentGomila** [comment]
> Are you sure it is getSize() that sets the eof flag

No, that's not what I meant. It is indeed ```read``` that puts the stream in an invalid state, and ```getSize``` is the next call, ie. the one that fails.

> By the way, is there a reason why we compute the file size every time getSize() is called, instead of storing it?

Is there a reason we should do it? :)

> I'm currently looking into it.

The code is fine, it's just that the ogg/vorbis library reaches the end of the file (while opening the file, not even reading samples) for some reason, and then tries to do something with it (reset the read position?), but since the stream is in an invalid state it fails.

**Comment by eXpl0it3r** [comment]
After hours of debugging stuff I asked someone in #vorbis on IRC and after some tests it turns out that issue is the different stream "expectations".
We're using `std::ifstream` which will lock up in failing mode if you once read beyond EOF, while vorbis expects stdio behavior.

The reason that it failed with the provided examples is not the length of them, but that they are single-page truncated files. So when getting the first page while "opening" the file, EOF will be reached and the stream "locks" up.

**Comment by LaurentGomila** [comment]
So switching to FILE* would not be such a bad idea after all. Until we get our own low-level implementation. There's even an implementation ready in the InputStream tutorial.

**Comment by PiotrZ** [comment]
Hello

In my project I have experienced similar problem (I have found this topic looking for solution).
However, I had tried to play with code and somehow I have found solution (at least I hope - tested on Windows).

In read function callback, after reading from stream, I placed this small condition:

<code>
if (in.eof())
{
 in.clear();
}
</code>

Small ogg played with no problems (data loaded into memory) :)

**Comment by eXpl0it3r** [comment]
We're well aware of what the `clear` function does. The problem was more related to what kind of behavior libvorbis expected and the easiest way was to use the "FILE" API instead of C++ streams.
