### ISSUE TITLE
Interface inconsistency for Sprite and Shape

### ISSUE THREAD

**Issue by Breush** [LaurentGomila/SFML#868]
I noticed a inconsistency in the interface of setTexture() and getTexture().
This is clearly not a major issue, but it would be more consistent to fix this.

If this is accepted, fixing it breaks the current interface,
hence I recommend to postpone to some SFML 3.0.

A sf::Sprite takes a reference to a sf::Texture for the setter:
```
void setTexture (const Texture &texture, bool resetRect=false);
const Texture * getTexture () const;
```

A sf::RectangleShape (and other shapes) takes a pointer for the setter:
```
void setTexture (const Texture *texture, bool resetRect=false);
const Texture * getTexture () const;
```

Note: The motivation for this proposition is that
it would enable some easier templating (with no specialization). See below.

```
template<typename T> void init(T& visual, TextureID textureID)
{
    object.setTexture(textureManager.get(textureID));
    object.setPosition(50.f, 50.f);
}
```

**Comment by binary1248** [comment]
They are not supposed to have the same interface. An `sf::Sprite` __must__ have a texture set for it, it is an invariant. `sf::RectangleShape` on the other hand doesn't have to have a texture, and therefore allows passing a `NULL` pointer which has the effect of unsetting the `sf::RectangleShape`'s texture to nothing (i.e. only being coloured).

Next time please use the forum for such "issues". This could have easily been answered there instead of the tracker, which is primarily for confirmed issues.
