### ISSUE TITLE
FindSFML module cannot find SFML.

### ISSUE THREAD

**Issue by IMMZ** [LaurentGomila/SFML#873]
FindSFML module incorrectly finds SFML version.
I have installed SFML 2.1 on my Xubuntu 14.04 machine.
<b>dpkg's output</b>: 'ii  libsfml-dev:i3 2.1+dfsg-4ub i386         Simple and Fast Multimedia Librar'
<b>My CMakeLists.txt has next line</b>: 'find_package(SFML 2 COMPONENTS system graphics)'
<b>When I run cmake I get next error</b>: 'SFML found but version too low (requested: 2, found: 1.x.x)'
<b>Config.hpp file defines version as next:</b>

////////////////////////////////////////////////////////////
// Define the SFML version
////////////////////////////////////////////////////////////
#define SFML_VERSION_MAJOR 2
#define SFML_VERSION_MINOR 1

It seems that regex on line 92 of FindSFML.cmake works incorrectly.
message("${SFML_CONFIG_HPP_CONTENTS}") after this regex shows empty line.

**Comment by TankOs** [comment]
What about `find_package(SFML 2.1 ...)`?

**Comment by binary1248** [comment]
The newer `FindSFML.cmake` requires a patch version to be present in `Config.hpp`, so unfortunately using a newer (>= 2.2) version of `FindSFML.cmake` to find an older version (< 2.2) of SFML won't work. If you need to find 2.1 you'll have to use a 2.1 `FindSFML.cmake`. Since the current version scheme will probably stay this way for quite a while, there is nothing for us to "fix" regarding forward compatibility. Using a mismatching `FindSFML.cmake` is not recommended anyway, since the list of static library dependencies is very likely to mismatch what the library really needs.

**Comment by IMMZ** [comment]
<b>TankOs</b>, your version gives same error: requested 2.1, found 1.x.x.
<b>binary1248</b>, I've checkout git repo to tag 2.1, got new FindSFML.cmake and replaced my old one. Now it works OK. Thanks for solution.
